### ISSUE TITLE
Akka inefficiencies + design choices

### ISSUE THREAD

**Issue by azell** [RuedigerMoeller/remoting-benchmarks#1]
I have some detailed feedback regarding the benchmarks implementation as it pertains to Akka performance.  Is a git issue the best way to track it?

**Comment by RuedigerMoeller** [comment]
cool. its your choice. I am fine with a git issue, however if we are going
to argue back and forth it might be appropriate to first mail and then post
a consolidated issue.

kind regards,
rüdiger (moru0011)

at gmail.com

2015-06-29 2:22 GMT+02:00 Adam Zell notifications@github.com:

**Comment by RuedigerMoeller** [comment]
?
